import os
import random
import string
# generate a file of passwords generated by an computer 
working_dir = os.getcwd()

passwords = []

def generate_passwords(passwords):
    # generate passwords
    # write the passwords to a file
    with open(f"{working_dir}\\passwords.txt", "w") as f:
        for password in passwords:
            # write the passwords to the file one by line
            f.write(f"{password}\n")



def main():
    # generate passwords with random characters and numbers and characters 
    def gen():
        password = ""
        # generate a password with 8 characters to 16 characters
        for i in range(random.randint(8, 16)):
            # generate a random character from the string module
            password += random.choice(string.ascii_letters + string.digits)
        return password
        
    for i in range(1000000):
        passwords.append(gen())
    generate_passwords(passwords)
                        
if __name__ == "__main__":
    main()
                        